# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
$ ->
  console.log("test")

allImages = ''

getRandomSize = (min, max) ->
  Math.round Math.random() * (max - min) + min

i = 0
while i < 25
  width = getRandomSize(200, 400)
  height = getRandomSize(200, 400)
  allImages += '<img src="https://placekitten.com/' + width + '/' + height + '" alt="pretty kitty">'
  i++

#Ali: This file can be deleted, I just saved it for future help on JS vs COFFEE
$ ->
  $('#photosss').append allImages


# ---
# generated by js2coffee 2.2.0
